[SERVICE]
    flush           1
    daemon          off
    log_level       ${LOG_AGENT_LEVEL}
    parsers_file    /fluent-bit/etc/parsers.conf

[INPUT]
    name            tail
    path            ${LOG_AGENT_FILE}
    tag             log-agent.logs
    read_from_head  false
    refresh_interval 5
    rotate_wait     30
    skip_long_lines on
    db              /tmp/flb_tail.db
    parser          try_json

[FILTER]
    name            lua
    match           log-agent.logs
    script          /fluent-bit/etc/transform.lua
    call            transform

[OUTPUT]
    name            http
    match           log-agent.logs
    host            ${LOG_AGENT_HOST}
    port            ${LOG_AGENT_PORT}
    uri             /api/v1/logs/ingest
    format          json
    json_date_key   false
    header          Authorization Bearer ${LOG_AGENT_API_KEY}
    header          X-MT-Source agent
    header          Content-Type application/json
    tls             ${LOG_AGENT_TLS}
    tls.verify      ${LOG_AGENT_TLS_VERIFY}
    retry_limit     ${LOG_AGENT_RETRY_LIMIT}
