package otelconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateIncludesDefaultReceiversAndPipelines(t *testing.T) {
	content := Generate(Options{ServiceName: "api"})

	required := []string{
		"receivers:",
		"otlp:",
		"hostmetrics:",
		"docker_stats:",
		"filelog:",
		"processors:",
		"resource/everyup:",
		"pipelines:",
		"metrics:",
		"logs:",
		"traces:",
	}
	for _, item := range required {
		if !strings.Contains(content, item) {
			t.Fatalf("generated config missing %q:\n%s", item, content)
		}
	}
}

func TestGenerateIncludesEveryUpWebExporter(t *testing.T) {
	content := Generate(Options{
		ServiceName:     "api",
		WebOTLPEndpoint: "https://everyup.example.com/api/v1/otlp/",
		WebAPIKey:       "secret",
	})

	if !strings.Contains(content, "otlphttp/everyup_web:") {
		t.Fatalf("missing web exporter:\n%s", content)
	}
	if !strings.Contains(content, `endpoint: "https://everyup.example.com/api/v1/otlp"`) {
		t.Fatalf("endpoint was not normalized:\n%s", content)
	}
	if !strings.Contains(content, `Authorization: "Bearer secret"`) {
		t.Fatalf("missing authorization header:\n%s", content)
	}
}

func TestValidateRequiresEndpointWhenAPIKeyIsSet(t *testing.T) {
	err := Validate(Options{ServiceName: "api", WebAPIKey: "secret"})
	if err == nil {
		t.Fatal("expected validation error")
	}
}

func TestWriteFileCreatesConfig(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated", "otel-config.yaml")
	err := WriteFile(Options{ServiceName: "api", OutputPath: path})
	if err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile returned error: %v", err)
	}
	if !strings.Contains(string(data), "Generated by EveryUp Agent") {
		t.Fatalf("generated file missing header:\n%s", string(data))
	}
}
