package otelconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Options struct {
	ServiceName string

	OutputPath string
	ConfDir    string

	HostMetricsEnabled  bool
	DockerStatsEnabled  bool
	FileLogEnabled      bool
	FileLogInclude      []string
	OTLPReceiverEnabled bool

	WebOTLPEndpoint string
	WebAPIKey       string
}

func (o Options) WithDefaults() Options {
	if o.OutputPath == "" {
		o.OutputPath = "/etc/everyup/generated/otel-config.yaml"
	}
	if o.ConfDir == "" {
		o.ConfDir = "/etc/everyup/conf.d"
	}
	if o.ServiceName == "" {
		o.ServiceName = "everyup-agent"
	}
	if len(o.FileLogInclude) == 0 {
		o.FileLogInclude = []string{"/var/lib/docker/containers/*/*.log"}
	}
	if !o.HostMetricsEnabled && !o.DockerStatsEnabled && !o.FileLogEnabled && !o.OTLPReceiverEnabled {
		o.HostMetricsEnabled = true
		o.DockerStatsEnabled = true
		o.FileLogEnabled = true
		o.OTLPReceiverEnabled = true
	}
	return o
}

func Generate(o Options) string {
	o = o.WithDefaults()
	var b strings.Builder

	b.WriteString("# Generated by EveryUp Agent. Manual overrides belong in ")
	b.WriteString(o.ConfDir)
	b.WriteString(".\n")
	b.WriteString("receivers:\n")
	if o.OTLPReceiverEnabled {
		b.WriteString(`  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
`)
	}
	if o.HostMetricsEnabled {
		b.WriteString(`  hostmetrics:
    root_path: /hostfs
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
`)
	}
	if o.DockerStatsEnabled {
		b.WriteString(`  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 30s
`)
	}
	if o.FileLogEnabled {
		b.WriteString("  filelog:\n")
		b.WriteString("    include:\n")
		for _, include := range o.FileLogInclude {
			b.WriteString("      - ")
			b.WriteString(quoteYAML(include))
			b.WriteString("\n")
		}
		b.WriteString(`    start_at: end
    include_file_path: true
`)
	}

	b.WriteString("\nprocessors:\n")
	b.WriteString(`  batch:
  resource/everyup:
    attributes:
      - key: everyup.agent.service
        value: `)
	b.WriteString(quoteYAML(o.ServiceName))
	b.WriteString(`
        action: upsert
`)

	b.WriteString("\nexporters:\n")
	b.WriteString(`  debug:
    verbosity: basic
`)
	if strings.TrimSpace(o.WebOTLPEndpoint) != "" {
		b.WriteString("  otlphttp/everyup_web:\n")
		b.WriteString("    endpoint: ")
		b.WriteString(quoteYAML(strings.TrimRight(o.WebOTLPEndpoint, "/")))
		b.WriteString("\n")
		if strings.TrimSpace(o.WebAPIKey) != "" {
			b.WriteString("    headers:\n")
			b.WriteString("      Authorization: ")
			b.WriteString(quoteYAML("Bearer " + o.WebAPIKey))
			b.WriteString("\n")
		}
	}

	receivers := enabledReceivers(o)
	exporters := []string{"debug"}
	if strings.TrimSpace(o.WebOTLPEndpoint) != "" {
		exporters = append(exporters, "otlphttp/everyup_web")
	}

	b.WriteString("\nservice:\n")
	b.WriteString("  pipelines:\n")
	b.WriteString(pipelineYAML("metrics", filterReceivers(receivers, "hostmetrics", "docker_stats"), exporters))
	b.WriteString(pipelineYAML("logs", filterReceivers(receivers, "filelog", "otlp"), exporters))
	b.WriteString(pipelineYAML("traces", filterReceivers(receivers, "otlp"), exporters))

	return b.String()
}

func WriteFile(o Options) error {
	o = o.WithDefaults()
	if err := Validate(o); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(o.OutputPath), 0o755); err != nil {
		return fmt.Errorf("create otel config directory: %w", err)
	}
	if err := os.WriteFile(o.OutputPath, []byte(Generate(o)), 0o644); err != nil {
		return fmt.Errorf("write otel config: %w", err)
	}
	return nil
}

func Validate(o Options) error {
	o = o.WithDefaults()
	if strings.TrimSpace(o.OutputPath) == "" {
		return fmt.Errorf("output path is required")
	}
	if strings.TrimSpace(o.ServiceName) == "" {
		return fmt.Errorf("service name is required")
	}
	if strings.TrimSpace(o.WebAPIKey) != "" && strings.TrimSpace(o.WebOTLPEndpoint) == "" {
		return fmt.Errorf("web OTLP endpoint is required when web API key is set")
	}
	return nil
}

func enabledReceivers(o Options) []string {
	var receivers []string
	if o.OTLPReceiverEnabled {
		receivers = append(receivers, "otlp")
	}
	if o.HostMetricsEnabled {
		receivers = append(receivers, "hostmetrics")
	}
	if o.DockerStatsEnabled {
		receivers = append(receivers, "docker_stats")
	}
	if o.FileLogEnabled {
		receivers = append(receivers, "filelog")
	}
	return receivers
}

func filterReceivers(receivers []string, allowed ...string) []string {
	allowedSet := make(map[string]bool, len(allowed))
	for _, item := range allowed {
		allowedSet[item] = true
	}
	filtered := make([]string, 0, len(receivers))
	for _, receiver := range receivers {
		if allowedSet[receiver] {
			filtered = append(filtered, receiver)
		}
	}
	return filtered
}

func pipelineYAML(name string, receivers []string, exporters []string) string {
	if len(receivers) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("    ")
	b.WriteString(name)
	b.WriteString(":\n")
	b.WriteString("      receivers: [")
	b.WriteString(strings.Join(receivers, ", "))
	b.WriteString("]\n")
	b.WriteString("      processors: [resource/everyup, batch]\n")
	b.WriteString("      exporters: [")
	b.WriteString(strings.Join(exporters, ", "))
	b.WriteString("]\n")
	return b.String()
}

func quoteYAML(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}
